[package]
name = "quaso"
version = "0.60.0"
edition = "2024"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Toolset for making Micro Games quickly"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/quaso"
repository = "https://github.com/PsichiX/quaso"
documentation = "https://docs.rs/quaso"
readme = "README.md"

[features]
default = ["editor"]
agent = []
debug_automatic_glGetError = [
    "spitfire-glow/debug_automatic_glGetError",
    "spitfire-draw/debug_automatic_glGetError",
    "spitfire-gui/debug_automatic_glGetError",
]
editor = []

[dependencies]
spitfire-core = "0.38"
spitfire-glow = "0.38"
spitfire-fontdue = "0.38"
spitfire-draw = "0.38"
spitfire-input = "0.38"
spitfire-gui = "0.38"
raui-core = "0.70"
raui-material = "0.70"
raui-immediate = "0.70"
raui-immediate-widgets = "0.70"
intuicio-data = "0.53"
intuicio-core = "0.53"
intuicio-derive = "0.53"
intuicio-backend-vm = "0.53"
ankha = "0.3"
ankha-auri = "0.3"
randscape = "0.4"
anput = "0.25"
moirai = "0.8"
moirai-pump = "0.8"
keket = "0.21"
nodio = "0.5"
emergent = "1.9"
tehuti = "0.23"
tehuti-client-server = "0.23"
tehuti-timeline = "0.23"
tehuti-socket = "0.23"
tehuti-web-transport = "0.23"
tehuti-diagnostics = "0.23"
typid = "1"
image = { version = "0.25", default-features = false, features = [
    "png",
    "gif",
    "webp",
    "jpeg",
] }
fontdue = "0.9"
vek = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
toml = "1.0"
noise = "0.9"
rand = "0.10"
kira = "0.12"
rstar = "0.13"
gilrs = { version = "0.11", features = ["serde-serialize"] }
anim8 = "1.5"
rusty_spine = "0.8"
zip = { version = "8.0", default-features = false, features = ["deflate"] }
tracing = "0.1"
tracing-subscriber = "0.3"
send_wrapper = "0.6"
gltf = { version = "1.4", features = ["names", "extras", "utils"] }
base64 = "0.22"
flume = "0.12"
paste = "1"
schemars = "1.2.2"
winit = { version = "0.30", features = ["serde"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1", features = ["wasm-bindgen"] }
getrandom = { version = "0.4", features = ["wasm_js"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Navigator"] }
js-sys = "0.3"
tracing-web = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = { version = "0.4" }
